ALTER TABLE "Ad" ADD COLUMN IF NOT EXISTS "targetZones" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Ad" ADD COLUMN IF NOT EXISTS "targetSegments" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Ad" ADD COLUMN IF NOT EXISTS "targetShopIds" JSONB NOT NULL DEFAULT '[]';
