ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "surgePricingMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "platformServiceFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
